[book]
title = "DataConfig Book"
description = "Serialization framework for Unreal Engine Property System that just works!"
src = "Source"
language = "en"

[output.html]
theme = "Theme"
additional-css = ["custom.css"]
site-url = "/dataconfig/"
git-repository-url = "https://github.com/slowburn-dev/DataConfig"

[output.html.fold]
enable = false
level = 0